---
- name: restart httpd
  ansible.builtin.systemd:
    name: httpd
    state: restarted

- name: restart php-fpm
  ansible.builtin.systemd:
    name: php-fpm
    state: restarted

- name: restart mariadb
  ansible.builtin.systemd:
    name: mariadb
    state: restarted
